# Generated by Django 5.2.14 on 2026-06-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_rename_token_reward_contentcontribution_reward_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Availability Slot', 'verbose_name_plural': 'Availability Slots'},
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='date',
            field=models.DateField(default='2026-06-01'),
        ),
    ]
