# Generated by Django 5.2.6 on 2025-09-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mentor', 'Mentor'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mentor', 'Mentor'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
