# Generated by Django 5.2.6 on 2025-09-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_base_role_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='base_role',
        ),
    ]
