# Generated by Django 5.2.14 on 2026-06-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='previous_experience',
            field=models.BooleanField(blank=True, null=True, verbose_name='Previous Experience'),
        ),
    ]
