# Generated by Django 5.2.14 on 2026-06-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_previous_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='career_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photos/'),
        ),
    ]
